### ISSUE TITLE
Affichage d'embed - Page de Modération

### ISSUE THREAD

**Issue by Tellvex** [DraftBot/Documentation#40]
### Problème

La page de configuration de l'autosanction n'existe pas, donc l'embed ne doit pas être là. De plus, on remarque que la page renvoie sur un fichier inexistant directement dans GitHub.

### Illustration du problème

![image](https://user-images.githubusercontent.com/78918215/236453876-cb76f7df-77a5-4ec7-bfc0-8cc4416e3d6f.png)

**Comment by Tellvex** [comment]
J'assigne @Hugo-broc sur l'issue car il est à l'origine de la dernière PR sur cette page

**Comment by Hugo-broc** [comment]
Yes, pas de problème !
Si tu as des questions, n'hésite pas 👍
Je regarderai ça au fur et à mesure...

**Comment by DraftProducts** [comment]
Si Il t'as assigné, c'est certes pas formel mais c'est pour te demander de t'en occuper @Hugo-broc 🤣
